### ISSUE TITLE
Isn't this dangerous regarding one's account on Letterboxd?

### ISSUE THREAD

**Issue by thebromas12** [romanbird/letterboxd-friends#3]
I'm afraid of asking Letterboxd so many petitions for like, idk, 3 hours (1000 movies per minute for a lot of movies) because they could think it's some kind of suspicious activity, right? Or that isn't actually a problem on Letterboxd? I just don't want to be banned or something because I'm just getting my friend's (there are a lot of them) average on the site.

**Comment by romanbird** [comment]
Probably fine: it doesn't use any api and its not actually linked to your username (all public information)
